[
  ./extensions/jetbrains-ld.nix
  ./extensions/xpad-console-filter.nix
  ./services/borgbackup.nix
  ./services/cec.nix
  ./services/homeassistant.nix
  ./services/itchiodevtest.nix
  ./services/kodi.nix
  ./services/kwin-session.nix
  ./services/lirc.nix
  ./services/mowbark-rf.nix
  ./services/ollama.nix
  ./services/steam.nix
]
